### ISSUE TITLE
Release won't create a new release because "no changes happened"

### ISSUE THREAD

**Issue by austinkregel** [vercel/release#94]
I'm running `release v1.2.3`. 

My issue is when I run `release` on a repo that has had commits since the previous tag was released it thinks that no changes have happened. The attached image demonstrates what I'm talking about a bit better.
![image](https://user-images.githubusercontent.com/5355937/27872524-106e10f0-6177-11e7-900b-f377a57804f5.png)
My commit `98ce847` is about 2 hours old when I took this screenshot, and as you can see there are 3 commits after it, those being `1e71bf6`, `68d46d2`, and `cc7ce64`. For some reason Release isn't picking up on these changes.

If I'm too vague on this please let me know I'll try to fill you in more

**Comment by aesopwolf** [comment]
You need to run `git tag <version>` first. Not too intuitive in my opinion. I would prefer it if the tag was cut automatically after the interactive selections.

**Comment by leo** [comment]
Also we don't support v-prefixed version tags at the moment, I think.

**Comment by chevinbrown** [comment]
I run into the same problems. tag +1, then run `release`.

It seems to miss n-1 merges...so if I've got a tag with 2 merged PRs, I'll only get a prompt for 1 change.

**Comment by chevinbrown** [comment]
@leo is this fixed?

**Comment by leo** [comment]
@chevinbrown Are you using a `v`-prefixed version?

**Comment by chevinbrown** [comment]
We are, yes.

**Comment by leo** [comment]
@chevinbrown I see. And since we're not planning to support that, we cannot fix this. 😊 

If the same error occurs without the prefix, please let me know and I'll look into it!

**Comment by king601** [comment]
Hi guys, I recently added this to another project and did two things...

1) Tagged with `git tag 1.0.0` and manually created the release notes for that tag.

2) Merged something in, and tagged with `git tag 1.0.1` tried to run `release` and I'm getting No changes since last release now.

![image](https://user-images.githubusercontent.com/1741179/31296856-74d80372-aaa9-11e7-9281-99988917f9b2.png)
Here's a screenshot of my terminal of the commands I ran when i tried to tag 1.0.1

![image](https://user-images.githubusercontent.com/1741179/31296895-977124cc-aaa9-11e7-92e3-79df411b07c0.png)

**Comment by rauchg** [comment]
That definitely sounds like an issue. We'll take a look @king601

**Comment by chevinbrown** [comment]
@rauchg--we use release many times daily. Fixing this would be a huge help. 😄

**Comment by rauchg** [comment]
So do we and we somehow have not encountered this issue. PRs welcome in the mean time.

**Comment by hoodwink73** [comment]
I think the issue which @king601 refers, uses `Version 1.0.0` as the first release tag. And it is not a valid semver tag. Hence the error.

And either way, this would not be a problem for newer projects as `release` now handles creating the initial release tag #112.

If there is no other related concern, I think we may close the issue here.

**Comment by chevinbrown** [comment]
@hoodwink73 we've just re-tagged our last release as `3.0.0`, and release _still_ does not pick up last n releases. Instead, it does `n-1`, somehow forgetting the last-merged PR.

Is this something we are doing? Seems like a bug b/c it's happening across multiple projects and environments.
